grpcio: Autospec creation for update from version 1.33.2 to version 1.34.0
AJ Heller (1):
      Make generate_projects.sh fail earlier on job errors

Aleksandr Dankovtsev (1):
      update required minimal php version to 7.0

Alex Merry (1):
      Fix undefined behavior when Python plugin is given no args

Alexander Polcyn (2):
      Allow --qps_server_target_override to configure clients even if the driver isn't configuring any servers
      Include stddef.h in address_sorting.h

Alisha Nanda (3):
      Added ADDRESS_NAME arg to resolver.h.
      Move include statements back to original positions.
      Fixed syntax error in GRPC_ARG_ADDRESS_NAME definition

Ashitha Santhosh (1):
      Fix compilation errors after clang-tidy upgrade.

Ben Reed (2):
      Add --server_port flag to python benchmark worker
      Make python qps_worker --server_port consistent

Benjamin Shaya (1):
      Add support for "unix-abstract:" URIs to support abstract unix domain sockets

Chengyuan Zhang (30):
      Add message and service definition for querying test client's real-time stats.
      Add message and service definition for updating test client's configuration dynamically.
      Update configure RPC request parameters.
      Add empty message definitions for real-time stats service and configure service.
      Delete an empty line.
      Update stats RPC service definition.
      No need to count succeeded RPCs for each peer separately.
      Implement the basic test case for limiting max number of concurrent RPCs.
      Update test description.
      Move circuit_breaking from _TEST_CASES to _ADDITIONAL_TEST_CASES as not all languages have the feature ready.
      Directly use enum values defined in the message instead of doing string conversion.
      Eliminate unnecessary wait_until_all_rpcs_fail
      Use _WAIT_FOR_BACKEND_SEC as the timeout for waiting a specific number of RPCs to be in-flight.
      Simplify test logic by only checking the number of RPCs being in-flight.
      Fix formatting.
      Formatting.
      Ensure number of outstanding RPCs being stable.
      Implement advanced circuit breaking test
      Categorize accumulated stats by methods.
      Enable running circuit_breaking_test_advanced.
      Configure client to send both unary and empty calls.
      Implement more advanced circuit breaking test with two backend services.
      Update test description.
      Only disable config validation for circuit breaking test.
      Enhance logging messages.
      Fix lint, formatting.
      Use two extra backend services for circuit breaking test.
      Perform circuit breaking test with dedicated backend services.
      Fix formatting.
      Merge pull request #24779 from voidzcy/impl/set_circuit_breaking_env_var_in_test_env

Christian Maurer (1):
      Remove conversion warning by static casting

Chuan Ren (4):
      Add implementation of base external account credentials
      Add url-sourced external credentials
      Add file-sourced external credentials
      Add aws signature v4 signer

Damon (1):
      Include ares_android.(c|h) in the build config.

Donna Dionne (10):
      Bump version to v1.34.x
      Bump version to v1.34.x: regenerate projects
      Protecting the circuit breaking (drop action) using environment
      Setting timeout in method config.
      Passing repo manager to markdroth
      Adding v1.33.1 to test matrix
      Adding v1.33.2 to test matrix
      Add option to priority policy to ignore reresolution requests from a given child.
      Protect timeout feature under a flag and added testing.
      Fixing a bug in cpp xds interop client after the use of absl::GetFlag

Easwar Swaminathan (3):
      interop: Enable Go modules support
      remove calls to deps
      try setting GO111MODULE in interop test runner

Eric Anderson (1):
      Update grpc-java to 1.32.2 in the interop_matrix

Eric Gribkoff (3):
      Make it possible to use pre-existing client processes
      yapf
      Merge pull request #24797 from ericgribkoff/less_backends

Erwin de Haan (1):
      Make RIDs for the native dependencies in Grpc.Core arch specific

Esun Kim (75):
      Delete slice_traits.h
      Bump iOS and OSX version
      Removing TLS workaround for Android NDK r12b.
      Replace grpc_shutdown_blocking with grpc_shutdown
      Upgrade six 1.15
      Add GPR_STDCPP_TLS
      Use STDCPP_TLS for major platforms
      Rebuild manylinux images to include python 3.9
      Clean up DEPLOYMENT_TARGET
      Disable C++ TLS on iOS temporarily
      Using comp_db for clang-tidy
      Fix clang-tidy errors
      Update by review
      Use clang-tidy 7
      Fix clang-tidy errors
      Bump to clang-tidy-8
      Normalize clang-tidy
      Revert "Disable C++ TLS on iOS temporarily"
      Added abseil-* to clang-tidy
      Fix abseil-* clang-tidy errors
      Enable readability-container-size-empty
      Fix code by readability-container-size-empty
      Enable modernize-use-bool-literals
      Fix by modernize-use-bool-literals
      Eanble bugprone-forward-declaration-namespace and bugprone-misplaced-widening-cast
      Upgrade clang-format-8
      Fix by clang-format-8.
      Enable modernize-make-unique
      Fix by modernize-make-unique
      Enable modernize-use-override
      Fix by tidy-modernize-use-override
      Enable readability-redundant-smartptr-get
      Fix by readability-redundant-smartptr-get
      Fix pagination in upload_rbe_results
      Bump MACOSX_DEPLOYMENT_TARGET to 10.10 for Ruby
      Bump MACOSX_DEPLOYMENT_TARGET to 10.10 for Python
      Enable readability-string-compare
      Enable readability-redundant-control-flow
      Fix by tidy-readability-redundant-control-flow
      Fix by readability-string-compare
      Enable misc-unused-using-decls
      Fix by misc-unused-using-decls
      Enable misc-definitions-in-headers
      Fix by misc-definitions-in-headers
      Enable google-default-arguments
      Fix for google-default-arguments
      Reformat source
      Fix errors in doxygen param descriptions
      Clean up WriteOptions cctor
      Fix check_trailing_newlines bug
      Upgrade Abseil to LTS 2020923.2
      Generating projects
      Address TSAN problem with Abseil.
      Disable XdsRoutingApplyXdsTimeout test under TSAN
      Enable XdsRoutingApplyXdsTimeout again under TSAN
      Remove xcode pinning
      Conditional GPR_STDCPP_TLS on Apple
      Upgrade cocoapods
      Disable XdsRoutingApplyXdsTimeout under Asan too
      Upgrade kokoro VM image
      Add stack-tracer to gRPC
      Enable google-global-names-in-headers
      Add .bazelignore
      Enable GPR_ABSEIL_SYNC on Apple
      Disable debugging-test in Release
      Disable debugging-test when running with MUSL
      Enable Abseil crash handler on Windows
      Add workaround for bazel
      Remove XDS size test
      Disable uds-abstract tests on mac
      Python3 ios_bin/binary_size.py
      Add a workaround for CERTIFICATE_VERIFY_FAILED
      To karthikravis
      Disable ASSERT_EQ in ConnectLoop on Mac
      Revert "Enable GPR_ABSEIL_SYNC on Apple"

Jan Tattermusch (36):
      add extract_metadata_from_bazel_xml.py explainers
      address review comments
      add examples of output at individual steps
      add extra comments and TODOs
      use e2 instances in GCE creation scripts
      RBE: rely on labels to select the right worker pool
      buildifier format
      modernize HelloworldXamarin example
      add copyright headers to Xamarin example
      build C# nugets on linux instead of windows for simplicity
      disable grpc_build_packages.bat
      dont include x86 grpc_csharp_ext for linux and mac
      adjust unitypackage
      remove C# jessie x86 dockerfile
      move native libraries targeting mobile to a separate Grpc.Core.Xamarin package
      introduce common.props, set LangVersion to 7.2
      add C# distribtest for .NET 5
      add netcoreapp3.1 C# distribtest
      fix Grpc.csproj build, add Grpc.csproj to the solution
      also add Grpc.Core.NativeDebug to the solution
      make qps_worker --server_port behavior consistent with java
      Stop relying on rbe-windows-credentials.json
      stop using GrpcTesting-d0eeee2db331.json for RBE authentication on linux
      improve check for Unity runtime
      upgrade dart interop SDK to 2.10
      remove useless grpc_interop_dart dockerfile template
      Revert "Resolve warnings and deprecations in several scripts in tools"
      unify OS detection logic between Grpc.Core.PlatformApis and Grpc.Tools
      unbreak ruby install by pinning brew gnupg
      add C# distribtest coverage for .NET5 single file publish
      fix native extension loading in .NET5 single-file deployments
      Load native extension on .NET core via differentiated DllImports
      simplify .NET framework loading logic
      generate go build_interop.sh from the template
      remove unused go1.7 image
      restore go1.8 image

Karthik Ravi Shankar (2):
      Move channel plugin from grpc_impl to grpc
      Pass repo manager to Donna

Lidi Zheng (30):
      Support pre-compiled Python 3.9 wheels
      Try to see what's wrong
      Use /passive mode instead of /quite mode
      Remove 3.9 Windows support
      Install Cython for Python 3.9 for artifact building jobs
      Ensure virtualenv is installed in new interpreters
      Fix the grpc.aio import hack and its unit test
      Build Python 3.9 artifacts for Linux x64 platforms
      Replace grpc_shutdown_blocking with grpc_shutdown in Cython
      Add support for unary-stream benchmarking for Python
      s/streamming/streaming/g
      Fix typo in Python's Windows build
      Add extra safe guard to prevent this function misbehave again
      Increase the timeout of Python basic tests on Windows
      Add a special optimization for 1 rpc unary-stream sync
      Stop the ctrl-c spam
      Add the empty line back
      Hard code the base of the string to decimal
      Explicitly set encoding to ascii to prevent TypeError in 3.7+
      Unify the encoding to ascii
      Change to explicitly encode
      Str and bytes have different interface...
      Resolve warnings and deprecations in several scripts in tools
      Upgrade yaml
      Add --ignore-installed
      Update build_cleaner
      Use Python3 for build_cleaner
      Explicitly import "util"
      Incur setuptools as an dependency for grpcio_tools
      Hopefully fixed 27 build on winserver2016

Mark D. Roth (32):
      Revert "Merge pull request #23524 from markdroth/xds_logging_revert"
      add dep.hpp dependency
      clang-format
      clang-format
      remove duplicate upbdefs files
      remove unused code
      update build files
      Change grpclb to wrap the subchannels instead of attaching the attributes to them.
      Don't keep address attributes on the resulting subchannels.
      xds: Add support for case_sensitive option in RouteMatch.
      Use a single instance of the drop and locality stats objects.
      update list of upbdefs files in build
      add missing dep
      clang-format
      appease clang-tidy
      fix upbdefs paths for non-bazel builds
      Improve ref-count tracing.
      Change service_config_test to use gmock ContainsRegex() matcher.
      Remove unnecessary dependencies for xds_cluster_manager LB policy.
      Move circuit breaking, EDS drops, and load reporting to xds_cluster_impl policy.
      Fix ADS server resource type version logic and refactor code.
      Fix xDS resource type version to persist across stream restarts.
      Change repo manager to nicolasnoble
      Use a global atomic for circuit breaking call counter.
      xds: Set status code to INVALID_ARGUMENT when NACKing.
      Create a separate object for each deadline timer.
      Fix msan bug in deadline filter.
      xds: Move channel creds creation into bootstrap parser.
      xds: Move use_v3 out of XdsApi, so that we can specify it on a per-server basis.
      Add XdsChannelCredsRegistry
      clang-tidy: enable google-readability-braces-around-statements
      Move resource generation out of ADS impl and into test suite class.

Massimiliano Torromeo (2):
      Do not build with boringssl ASM when using system openssl
      Allow grpcio to be built against system re2

Menghan Li (2):
      xds testing: add path matching and header matching to test desc
      Add v1.33.1 release of grpc-go to interop matrix

Michael Lumish (4):
      Update Node examples to use @grpc/grpc-js
      Add target argument to Node examples
      Add a Node xDS example client
      Node xDS example: show error on failure, close client when done

Moien Tajik (3):
      make main methods async
      remove unused namespaces from example classes
      fixed typo in method name: dependend -> dependent

Nathan Herring (1):
      Revert "Abseil Flags"

Nicolas 'Pixel' Noble (1):
      Passing to Esun.

Parveen Kumar (1):
      Specify a large value for max metadata size in grpc_cli client channel.

Patrice Chalin (2):
      Copyedits to release header
      Link to Python gRPC page on grpc.io

Richard Belleville (18):
      Remove uses of PIPE
      Get port properly
      Make Python2 an optional dependency
      Fix Python 2 build
      Clean up conditional
      Modernize run_codegen script
      Add -x to shell script
      Include well-known types in sys.path when using runtime protos
      Oops
      And remove it too
      Include well known types in bazel build
      Buildifier
      Switch names around
      Implement grpc.Future interface in SingleThreadedRendezvous
      Spruce up docstrings
      Add comment about timeout argument
      Avoid internal build failure
      Revert "Merge pull request #24568 from veblush/test-xds-abseil"

Sean Fausett (2):
      Fix to not require libc-dev on .NET 5 or later
      Use version agnostic symbol for NETSTANDARD

Sergii Tkachenko (1):
      Update grpc-java to 1.33.1 in the interop_matrix

Stanley Cheung (3):
      PHP: fix windows build error
      Bump version to 1.34.0-pre2
      Regenerate projects

Victor Titor (1):
      Fix mistyping in fork-support

Vijay Pai (8):
      Remove non-existent grpc_impl forward declaration
      Reduce templating for unary callback client RPC
      Reduce sync client templating for protobuf
      Also reduce templating for ClientUnaryReactor
      Reduce template use in server
      Reduce code paths
      Reduce templating for async client unary call codegen
      Remove internal use of deprecated ClientAsyncResponseReaderFactory

Yash Tibrewal (17):
      Sanitize cronet_status.cc - missing new line
      Add experimental XdsCredentials with support for insecure channel_credentials and security_connector
      Update transport socket name to envoy.transport_sockets.tls
      xDS bootstrap parsing changes for certificate providers
      Fix sanity on master
      CertificateProviderStore implementation
      Experimental support and tests for CreateCustomInsecureChannelWithInterceptorsFromFd
      Fix --define=grpc_no_xds=true build
      Revert "Revert "Deprecate GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS""
      Cleanup TlsCredentialsOptions
      Add XdsCertificateProvider
      iModify build script to add tests for --define=grpc_no_xds=true
      Re-enable testKeepaliveWithV2API
      Update bootstrap string for certificate providers
      Update CertificateProviderInstance passing to include certificate name
      File watcher certificate provider config parsing
      Protect xds security code with environment variable

ZHANG Dapeng (1):
      Update grpc-java to 1.33.0 in the interop_matrix

ZhenLian (4):
      Add Credential Loading From Static Providers For TLS Credentials
      fix a bug when parsing SAN fields
      add API to get last modification time of a file
      add a dummy name for other type of SAN

capstan (6):
      Use abseil's flags in tests.
      Python3-ize tools/buildgen.
      Rerun tools/buildgen/generate_projects.sh under Python 3.
      Roll forward of commit 7883b51: Use abseil's flags in tests.
      Retire flags
      Remove gflags.

mangogan-git (1):
      Update server_reflection.md

root (10):
      del php5 ifdefs from ext
      add special status msg interop test
      add ifdef for compiling on php8
      add a test dockerfile for php8
      upgrade to phpunit8
      upgrade to phpunit8.5.8
      to fit phpunit8 grammar, add void to setUpBeforeClass(), setUp() and tearDown()
      del test dockerfile for php 8 for now
      add php8 test docker
      upgrade phpunit to 8.5.8

yang-g (3):
      Check localhost is resolved to ipv4 or ipv6 and update test accordingly.
      Add missing dependency
      Remove hack for Xcode 10

yulin-liang (24):
      Add transport information into grpc-objc user-agent.
      Modify podfile of CFStreamTests.
      Increasing the number of available threads for iOS
      Attempt to extend timeout for ios-test-cfstream-tests.
      Extend time out for cfstream-test.
      Add some debug logs for flaky cfstream and cronet tests.
      Support swift package manager for grpc-core and grpc-cpp.
      unsafe flags
      update submodule boringssl-with-bazel with origin/master-with-bazel
      update boringssl dependency to master-with-bazel commit SHA
      renegerate files
      Updated sha256
      generate boringssl prefix headers
      Increment podspec version
      Second regeneration
      Extend the timeout for ios-cpp-test-cronet
      Fix flaky ios-cpp-test-cronet test.
      InitialMetadata callback shouldn't be triggered with empty initialMetadata.
      Fix ios flaky tests
      Bump version to V1.34.0-pre1
      bump core_version
      Regenerate projects
      Bump version to v1.34.0
      Regenerate projects