grpcio: Autospec creation for update from version 1.36.1 to version 1.37.0
AJ Heller (12):
      Teach the release notes script to find GitHub Squash and Merge PRs
      Fix unused variable error from PR #25401
      Document ownership transfer in ChannelArguments::SetPointerWithVtable (#25527)
      Remove the `urgent` argument from iomgr tcp read API (#25494)
      Revert "Remove the `urgent` argument from iomgr tcp read API (#25494)" (#25592)
      Migrate the bm_diff benchmarks to python3 (#25619)
      Increase artifact build timeouts for problem targets (#25695)
      Change repo mgr to @nicolasnoble (#25648)
      Add google storage URLs for all mirrored bazel dependencies (#25710)
      Create a go module for http2 interop test, fixing breakage from upgrade to go v1.16 (#25707)
      Fix python3 performance tests - incomplete migration from python2 (#25734)
      Fix invalid use of python's traceback.print_exc (#25743)

Aidan Wolter (2):
      [Fuchsia] Disable C-ARES resolver
      [Fuchsia] Fix root SSL cert path

Alexander Polcyn (4):
      Fix a race in resolve_address and resolve_address_posix tests
      Fix no free threads flake in ruby call creds timeout test
      Don't perform unnecessary RPCs in call creds timeout test
      Fix child process port selection in ruby end-to-end tests

Anatol Belski (1):
      cmake: Reflect minor version change in SONAME for C++ and C# (#25617)

Ashitha Santhosh (3):
      Increase max frame size to 1MB.
      Add getter to grpc_metadata_batch. (#25395)
      SDK authorization policy translator. (#25361)

Chengyuan Zhang (1):
      Update interop client matrix for grpc-java 1.31.2 and 1.32.3 releases. (#25747)

Clément Péron (1):
      Update third_party/benchmark to v1.5.2 (#25184)

Daren McCulley (1):
      replace deprecated addProtoService (#25536)

David Federman (1):
      [C#] Add buildTransitive directory to NuGet package

Doug Fawley (5):
      add timeout to xds test runs; prevent running V3/alpha tests
      run_xds_tests: use frozenset for const instead of set
      run_xds_tests: add fault_injection tests (#25641)
      testing: allow 10m for first xds fault_injection case (#25779)
      xds: enable fault_injection xds tests for C++ (#25769)

Eric Anderson (1):
      Add gRPC Java 1.36.0 to interop matrix (#25566)

Esun Kim (20):
      Add use_strict_warning=true for mac-os bazel rbe build
      Fix unused variable 'weak_refs'
      Revert "Made grpc_core::Mutex compatible to absl::Mutex"
      Made grpc_core::Mutex compatible to absl::Mutex
      Make grpcpp/mutex compatible absl/mutex
      Support MAC
      To karthikravis
      Added thread annotation (#25486)
      Replaced slice_shard:gpr_mu with Mutex (#25427)
      Changed RPI build test to general ARM build test (#25580)
      Add abseil thread annotations to grpcpp/sync (#25560)
      Upgrade clang-tidy and clang-format to 11 (#25590)
      Added include/grpcpp/impl/codegen/method_handler_impl.h to grpc++_codegen_base (#25618)
      Update clang-tidy checks (#25627)
      Fix readability-const-return-type,readability-delete-null-pointer,readability-simplify-boolean-expr (#25628)
      Replace deprecated thread annotations macros. (#25673)
      Fix bugprone unhandled self assignment (#25667)
      Fix status error (#25731)
      Added CMakeLists.txt to cpp/examples (#25692)
      Add g_gli_initializer to server_context (#25759)

Hannah Shi (3):
      PHP: php server commit 2/n, add Server Call (#25397)
      PHP: php server commit 3/n, add ServerContext and MethodDescriptor (#25399)
      Ruby: support for PSM security (#25330)

Ivan Inozemtsev (1):
      Update dart to 2.12 release (#25657)

Jan Tattermusch (27):
      remove useless vspackages section from build_handwritten.yaml
      remove useless build plugin "generate_vsprojects.py"
      use python27 specific pip in python dockerfiles
      fix getting pip for python3.5
      regenerate dockerfiles
      remove no-longer-needed fuzzer dockerfile
      update dotnet sdk5 docker image to avoid nuget download error
      minor adjustments
      pin version of gcr.io/oss-fuzz-base/base-builder
      use boringssl asm optimizations in aarch64 wheel source build
      C#: Use explicit native extension loading whenever possible (#25490)
      Simplify build.yaml's  "deps_linkage" logic (#25521)
      get rid of dll_only in build.yaml (#25524)
      Cleanup: Remove no-longer-needed expand_filegroups.py (#25532)
      Update PHP's grpc_php_plugin instructions (#25544)
      fix typos in comments (#25546)
      use linkstatic for libraries that contain main() (#25517)
      Crosscompile python aarch64 wheels with dockcross (#25418)
      Improve Grpc.Tools documentation (#25570)
      Delete no longer needed artifact_linux dockerfiles (#25542)
      Assorted python wheel build improvements (#25602)
      simplify build.yaml: get rid of the "secure" field (#25547)
      add a job for end to end benchmarks V2 (#25732)
      make Grpc C# work on aarch64 linux (#25717)
      Use crosscompilation to build python armv7 wheels (#25704)
      Reduce Grpc.Core nuget size by generating separate .so with/without debug symbols for grpc_csharp_ext (#25729)
      extract_metadata_from_bazel_xml.py changes from #25272 (#25758)

Jeff Moser (1):
      Add support for additional protoc arguments in Grpc.Tools (#25374)

Karthik Ravi Shankar (3):
      Pass repo manager to Donna (#25523)
      Update boringssl (#25564)
      Update third_party/protobuf to v3.15.2 (#25565)

Levon Ter-Grigoryan (1):
      Fix implicit-int-float-conversion warning.

Lidi Zheng (26):
      Bump version to v1.37.0
      Regenerate projects
      Bump up minimum supported clang to 4.0
      Use template to generate the Dockerfile
      Fix a typo in xDS bootstrap parsing
      [xDS Proto] Pin PyPI dependencies in Dockerfiles (#25510)
      Update PyYAML in generate_project.sh if needed (#25563)
      Fix the generated_projects.sh again (#25572)
      [xDS Proto] Update Bazel dependencies (#25511)
      [xDS Proto] Modernize buildgen scripts (#25512)
      Make returning a local reference a compilation error (#25568)
      Update config selector for LDS update with no route config (#25528)
      Fix build abseil/boringssl/protobuf at head (#25638)
      Implement xDS client-side fault injection filter (#24354)
      Fix a typo in fault injection (#25693)
      [Aio] Add time_remaining method to ServicerContext (#25719)
      Add gRPC 1.36.3 to the interop matrix (#25723)
      Mark Python interceptors as stable (#25739)
      CSDS Implementation (#25038)
      Revert "CSDS Implementation (#25038)" (#25745)
      Re-introduce "CSDS Implementation" (#25762)
      Implement C++ Admin Interface API (#25753)
      Add ExecCtx to channelz surface APIs (#25733)
      Remove fault injection environmental variable guard (#25792)
      Apply the xds-specific Bazel rule to admin API (#25799)
      Use Realtime instead of Monotonic time for CSDS (#25864)

Mark D. Roth (12):
      Use xDS v3 in google-c2p resolver.
      Upgrade xDS protos
      xDS HTTP filter support for gRPC client
      add env var protection for google-c2p resolver (#25548)
      xds_end2end_test: improve TestType API (#25557)
      xds_end2end_test: avoid flakes from lingering shutdown from previous test (#25561)
      Second attempt: xDS HTTP filter support for gRPC client (#25558)
      Change repo manager to drfloob. (#25637)
      xds: Fix handling of HTTP filter that does not set typed_config. (#25651)
      xds: Ignore HTTP filters if LDS resource is v2. (#25694)
      Add lock annotations in client_channel filter. (#25777)
      Add lock annotations in subchannel code. (#25780)

Menghan Li (3):
      Add v1.36.0 release of grpc-go to interop matrix (#25553)
      Disable fault injection env var in xds interop tests (#25676)
      xds testing: set fault injection env var, so the test can be turned on (#25735)

Minku Lee (1):
      ruby: add conditional on darwin based on arch (#25419)

Olivier Bellone (1):
      Include `GRPC::GenericService` from root namespace (#25153)

Paweł Wichary (1):
      Grpc.Tools readme update - duplicated .proto names (#22628)

Richard Belleville (20):
      Clarify the Future interface
      Integrate additional guarantee into existing statement
      Revert "Merge pull request #25365 from gnossen/python_xds_creds"
      Fix API
      Revert "Revert "Merge pull request #25365 from gnossen/python_xds_creds""
      Try to use Python 3
      Add backport script
      Readd commented git fetch
      Add copyright notice
      Enable backport of unmerged PRs (#25502)
      Fix Signal Safety Issue (#25394)
      Format Channelz Address.TcpIpAddress.address as packed bytes (#25629)
      Fix pypa link (#25647)
      Enable Python Timeout xDS Interop Test (#25525)
      Pin xDS interop test runner dependencies (#25665)
      Revert "Pin xDS interop test runner dependencies (#25665)" (#25768)
      Decrease Python xDS interop client verbosity. (#25661)
      Upmerge v1.36 to master (#25800)
      Bump to 1.37.0-pre1 (#25839)
      Bump to 1.37.0 for Final Release (#25891)

Sergii Tkachenko (8):
      xds-k8s driver: switch Backend Health Check from TCP to GRPC
      fixup! xds-k8s driver: switch Backend Health Check from TCP to GRPC
      xds-k8s driver: remove "Client subchannel must have no sockets" check (#25460)
      xds-k8s: set GRPC_XDS_EXPERIMENTAL_NEW_SERVER_API (#25529)
      xds-k8s: Update local-dev.cfg.example (#25552)
      Double WAIT_FOR_BACKEND_SEC (#25603)
      xds-k8s Fix NameError name 'cls' is not defined (#25615)
      xds-k8s: Update to TD bootstrap with server_listener_resource_name_template support (#25746)

Srini Polavarapu (1):
      add xds v3 feature (#25706)

Stanley Cheung (6):
      Ruby xds timeout test
      review fixes
      Replaces disrespectful terms (#25501)
      Fix access to empty list in proto (#25625)
      Enable timeout xds test for Ruby (#25623)
      PHP: remove experimental from Interceptor API (#25788)

Vijay Pai (16):
      Use AllocatingRequestMatcher for sync C++ server and simplify
      Implement callback CQ at C++ layer using shared thread pool if non-background iomgr
      Reduce max size of bm_callback_streaming_ping_pong messages to match unary
      Explain include/grpc++ vs include/grpcpp
      Fix unused param warning
      Remove an incorrect debug assertion
      Restore callback microbenchmarks but make them manual for now (#25491)
      Document reaction concurrency and reactor lifetime (#25481)
      Don't dynamically allocate default server context (#25576)
      Fix race at server shutdown between actual shutdown and MatchOrQueue (#25541)
      Add virtual destructor to ClientReactor base class (#25599)
      Thread annotations for C++ callback API headers (#25571)
      Annotate C++ server (#25605)
      Add usage note about immediately-Set alarms (#25678)
      Fix const-ness of callback client read RPC requests (#25763)
      clang-format C++ examples (#25764)

WANG Lei (1):
      Remove unused parameter from UnaryDeserializeHelper (#25332)

Yash Tibrewal (30):
      Replace disrespectful term
      Replace disrespectful words
      Remove disrespectful terms
      Remove disrespectful term
      Replace disrespectful term
      Add script to check for illegal terms
      Enable initiating writes for bdp pings
      Set error message when a data frame with END_STREAM is received on client
      Reduce log severity of cq operation failure message
      Disable check_call_host when server_verification_option is not GRPC_TLS_SERVER_VERIFICATION (#25577)
      Parse FilterChainMatch from LDS response (#25530)
      Option to disable local_certificate check from PSM security tests (#25595)
      Add missing security field to channelz Socket (#25593)
      xDS Interop Client changes for PSM security tests (#25613)
      Fix internal build (#25622)
      Disable channelz_service_test for iOS (#25639)
      C++ xDS interop test server changes (#25633)
      xDS status notifier (#25321)
      Some environments support only IPv6 addresses - followup from #25321 (#25656)
      Change Chttp2ServerListener to share the ref of the underlying grpc_tcp_server (#25655)
      Channelz security changes - Follow up from #25593 (#25624)
      xDS changes for server listener resource name template (#24965)
      Filters parsing logic for servers (#25609)
      Revert "xDS status notifier (#25321)" (#25702)
      Adding test to make sure that http2 transport gets cleaned up (#25714)
      Revert Revert Xds Status Notifier (#25718)
      Follow-up from #24965 (#25683)
      xDS LDS parsing changes: NACK on use_original_dst (#25687)
      Get URI form of address for channelz (#25785)
      Implement FilterChainMatch algorithm (#25757) (#25815)

Yonathan Randolph (1):
      grpc_cli: allow multiple colon-separated paths in --proto_path (#24187)

apolcyn (10):
      Relax ruby test check on protobuf error message (#25507)
      Allow C2P resolver's server_uri to be overridden for testing (#25551)
      Make --server_port optional in C++ interop client (#25550)
      Remove CAS loops in global subchannel pool and simplify subchannel refcounting (#25485)
      Fix an infinite read loop with SRV record resolution on windows (#25672)
      document --service_config_json flag in interop test descriptions (#25689)
      attempt to fix sporadic windows c-ares crash (#25726)
      Convert grpc_ares_wrapper to C++ (#25108)
      Revert "Convert grpc_ares_wrapper to C++ (#25108)" (#25761)
      Add ruby 3.0 support for mac binary packages (#25869)

crewmatt (1):
      Update csharp_generator.cc to be compatible with internal and public version of protobuf (#25514)

donnadionne (9):
      Revert "Made grpc_core::Mutex compatible to absl::Mutex" (#25537)
      Revert "Revert "Made grpc_core::Mutex compatible to absl::Mutex" (#25537)" (#25549)
      Revert "xDS HTTP filter support for gRPC client" (#25555)
      Passing repo manager to markdroth (#25589)
      Adding xxhash as a subtree (#25601)
      Revert "Adding xxhash as a subtree" (#25630)
      Adding xxhash as a subtree (#25645)
      Generating hash for ring_hash policy (#25415)
      Removing circuit_breaking and timeout environment variable guard to (#25793)

emkornfield (1):
      Standardize all environment variable boolean configuration in python's setup.py (#25444)

srini100 (1):
      add link to release support policy

yihuaz (1):
      add max_frame_size support to fake TSI handshaker and fake HS service (#25621)

yulin liang (2):
      In Doxygen-style comments, '@c @select()' is invalid now. (#25474)
      Fix required a higher minimum deployment target of Auth Sample Test (#25736)

yulin-liang (3):
      Support to add a suffix on user agents for grpc-objc.
      Extend timeout for streaming calls
      Test user agent suffix for grpc-objc.